#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Booking\BookingApplication;
use Booking\Console\Command\BookindLoadCommand;
use Booking\Console\Command\SalePersonCommand;
use Booking\Console\Command\MonitorCommand;

$application = new BookingApplication();
$application->add(new BookindLoadCommand());
$application->add(new SalePersonCommand());
$application->add(new MonitorCommand());
$application->run();
