grafana:
  image: grafana/grafana:2.5.0
  links:
    - influxdb:influxdb
  environment:
    GF_SERVER_ROOT_URL: http://localhost
    GF_SECURITY_ADMIN_PASSWORD: secret
  ports:
    - 3000:3000
  volumes:
    - "./grafana:/var/lib/grafana"

influxdb:
  hostname: influxdb
  image: tutum/influxdb:0.9
  environment:
    PRE_CREATE_DB: tickets
  ports:
    - 8083:8083
    - 8086:8086
  volumes:
    - "./influxdbData:/data"

amqp:
  hostname: rabbitmq
  image: rabbitmq:management
  ports:
    - 15672:15672
    - 5672:5672
  environment:
    RABBITMQ_NODENAME: test
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
  volumes:
    - "./rabbitmq:/var/lib/rabbitmq"